"""Tests for the newly-shipped features the docs used to call "planned":

* ``Blackboard.post_request`` + ``reply_to`` — request/reply pattern
* Async watcher fan-out on the Blackboard
* ``memory_tools()`` — LLM-callable ``remember_fact`` / ``forget_fact``
* ``SQLiteMemoryStore`` — stdlib sqlite3 backed MemoryStore, full
  bi-temporal parity with ``JSONMemoryStore``
"""

from __future__ import annotations

import threading
import time
from concurrent.futures import TimeoutError as FutureTimeout
from pathlib import Path

import pytest

from edgevox.agents.memory import JSONMemoryStore, SQLiteMemoryStore
from edgevox.agents.memory_tools import memory_tools
from edgevox.agents.multiagent import Blackboard

# ---------------------------------------------------------------------------
# Blackboard.post_request
# ---------------------------------------------------------------------------


class TestPostRequest:
    def test_reply_resolves_future(self):
        bb = Blackboard()
        fut = bb.post_request("plan.request", {"goal": "pick cup"})
        request = bb.get("plan.request")
        assert request["task"] == {"goal": "pick cup"}
        bb.reply_to(request, "mocked plan")
        assert fut.result(timeout=1.0) == "mocked plan"

    def test_volunteer_watches_request_key(self):
        """End-to-end: a volunteer watcher reacts to the post and
        sends back a reply — the canonical supervisor/worker loop."""
        bb = Blackboard()

        def volunteer(_k, _old, new):
            if isinstance(new, dict) and "task" in new:
                bb.reply_to(new, {"plan": f"executed {new['task']}"})

        bb.watch("plan.request", volunteer)
        fut = bb.post_request("plan.request", "sweep floor", timeout=1.0)
        result = fut.result(timeout=1.0)
        assert result == {"plan": "executed sweep floor"}

    def test_cancelled_future_unsubscribes_watcher(self):
        """If the caller cancels before the reply lands, no lingering
        watcher should remain — otherwise a late reply would try to
        resolve a cancelled Future and silently no-op, and the
        unbounded watcher list would leak over time."""
        bb = Blackboard()
        fut = bb.post_request("k", "t")
        reply_key = bb.get("k")["reply_key"]
        fut.cancel()
        # Wait a beat for the done-callback to run the unsubscribe.
        time.sleep(0.02)
        assert bb._watchers.get(reply_key, []) == []

    def test_late_reply_after_timeout_is_harmless(self):
        """Volunteer might finish work after the timeout expires. The
        Future is already in error state — we must not raise a second
        time or corrupt blackboard state."""
        bb = Blackboard()
        fut = bb.post_request("k", "t", timeout=0.05)
        with pytest.raises(FutureTimeout):
            fut.result(timeout=1.0)
        # A late reply after timeout is allowed (no exception from
        # the framework). It simply won't resolve the Future.
        reply_key = bb.get("k")["reply_key"]
        bb.set(reply_key, "too-late")
        # The late reply did set the blackboard key — that's ok.
        assert bb.get(reply_key) == "too-late"

    def test_custom_reply_key_is_honored(self):
        bb = Blackboard()
        fut = bb.post_request("req", "t", reply_key="my.explicit.reply")
        bb.set("my.explicit.reply", "answer")
        assert fut.result(timeout=1.0) == "answer"

    def test_reply_key_autogenerated_uniquely(self):
        bb = Blackboard()
        f1 = bb.post_request("plan", "t1")
        f2 = bb.post_request("plan", "t2")
        # Each request allocates its own reply_key, so replying to one
        # doesn't resolve the other.
        reqs = [bb.get("plan")]  # only the latest survives on the key
        assert reqs[0]["task"] == "t2"
        # Manually resolve f2's reply.
        bb.reply_to(reqs[0], "done-t2")
        assert f2.result(timeout=1.0) == "done-t2"
        assert not f1.done()
        f1.cancel()

    def test_timeout_fires_exception(self):
        bb = Blackboard()
        fut = bb.post_request("never.answered", "x", timeout=0.15)
        with pytest.raises(FutureTimeout):
            fut.result(timeout=1.0)

    def test_reply_to_rejects_non_envelope(self):
        bb = Blackboard()
        with pytest.raises(ValueError):
            bb.reply_to("not a dict", "result")
        with pytest.raises(ValueError):
            bb.reply_to({"no_reply_key": True}, "result")

    def test_watcher_unsubscribed_after_reply(self):
        bb = Blackboard()
        fut = bb.post_request("k", "t")
        assert bb.get("k")["reply_key"] in set(bb._watchers)
        bb.reply_to(bb.get("k"), "done")
        fut.result(timeout=1.0)
        # Unsub runs as a done-callback — the watcher list for that
        # reply key should be empty or gone.
        reply_key = bb.get("k")["reply_key"]
        assert bb._watchers.get(reply_key, []) == []


# ---------------------------------------------------------------------------
# Async watcher fan-out
# ---------------------------------------------------------------------------


class TestAsyncWatchers:
    def test_sync_blackboard_blocks_set_on_slow_watcher(self):
        bb = Blackboard()
        started = threading.Event()

        def slow(_k, _old, _new):
            started.set()
            time.sleep(0.2)

        bb.watch("x", slow)
        t0 = time.monotonic()
        bb.set("x", 1)
        elapsed = time.monotonic() - t0
        # Synchronous fan-out: ``set`` only returns after watcher finished.
        assert started.is_set()
        assert elapsed >= 0.15, f"expected sync dispatch to block ≥0.15 s, took {elapsed:.3f} s"

    def test_async_blackboard_does_not_block_set(self):
        bb = Blackboard(async_watchers=True)
        started = threading.Event()
        finished = threading.Event()

        def slow(_k, _old, _new):
            started.set()
            time.sleep(0.2)
            finished.set()

        bb.watch("x", slow)
        t0 = time.monotonic()
        bb.set("x", 1)
        set_elapsed = time.monotonic() - t0
        assert set_elapsed < 0.1, f"async ``set`` should return fast, took {set_elapsed:.3f} s"
        # The watcher still runs; wait for it.
        assert finished.wait(timeout=1.0)
        bb.close()

    def test_close_is_idempotent_on_sync_blackboard(self):
        bb = Blackboard()
        bb.close()
        bb.close()  # must not raise — pool was never created

    def test_watcher_exception_does_not_poison_pool(self):
        bb = Blackboard(async_watchers=True)
        raised = threading.Event()
        ok = threading.Event()

        def boom(_k, _old, _new):
            raised.set()
            raise RuntimeError("handler fail")

        def second(_k, _old, _new):
            ok.set()

        bb.watch("x", boom)
        bb.watch("x", second)
        bb.set("x", 1)
        assert raised.wait(timeout=1.0)
        assert ok.wait(timeout=1.0)
        bb.close()

    def test_many_concurrent_writes_land_all_watchers(self):
        """Under async mode, N simultaneous writers should each
        deliver to the watcher. No dropped events, no deadlock."""
        bb = Blackboard(async_watchers=True, max_watcher_workers=4)
        seen: list[int] = []
        lock = threading.Lock()

        def record(_k, _old, new):
            with lock:
                seen.append(new)

        bb.watch("x", record)

        def writer(n: int):
            for i in range(n):
                bb.set("x", i)

        threads = [threading.Thread(target=writer, args=(10,)) for _ in range(5)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        # Give the executor a moment to drain its queue.
        bb.close()
        assert len(seen) == 50

    def test_delete_triggers_watchers_too(self):
        """delete() should fan out just like set() — otherwise watchers
        can't observe cleanup events."""
        bb = Blackboard()
        observed: list[tuple] = []
        bb.set("k", 1)
        bb.watch("k", lambda k, old, new: observed.append((k, old, new)))
        deleted = bb.delete("k")
        assert deleted is True
        assert observed == [("k", 1, None)]


# ---------------------------------------------------------------------------
# memory_tools wrapper
# ---------------------------------------------------------------------------


class TestMemoryTools:
    def test_remember_persists_to_store(self, tmp_path: Path):
        store = JSONMemoryStore(tmp_path / "m.json")
        remember, _forget, _recall = memory_tools(store)
        result = remember.call({"key": "user.name", "value": "Ada"})
        assert "remembered" in result
        assert store.get_fact("user.name") == "Ada"

    def test_forget_revokes_fact(self, tmp_path: Path):
        store = JSONMemoryStore(tmp_path / "m.json")
        store.add_fact("user.name", "Ada")
        _, forget, _ = memory_tools(store)
        result = forget.call({"key": "user.name"})
        assert "forgot" in result
        assert store.get_fact("user.name") is None

    def test_forget_missing_key_reports(self, tmp_path: Path):
        store = JSONMemoryStore(tmp_path / "m.json")
        _, forget, _ = memory_tools(store)
        result = forget.call({"key": "never.set"})
        assert "nothing to forget" in result

    def test_recall_returns_value(self, tmp_path: Path):
        store = JSONMemoryStore(tmp_path / "m.json")
        store.add_fact("x", "42")
        _, _, recall = memory_tools(store)
        assert recall.call({"key": "x"}) == "42"

    def test_recall_missing_returns_explanatory_string(self, tmp_path: Path):
        store = JSONMemoryStore(tmp_path / "m.json")
        _, _, recall = memory_tools(store)
        result = recall.call({"key": "missing"})
        assert "no fact" in result

    def test_schemas_are_wellformed_openai(self, tmp_path: Path):
        store = JSONMemoryStore(tmp_path / "m.json")
        for t in memory_tools(store):
            schema = t.openai_schema()
            assert schema["type"] == "function"
            assert schema["function"]["name"] in {"remember_fact", "forget_fact", "recall_fact"}
            params = schema["function"]["parameters"]
            assert params["type"] == "object"
            assert "key" in params["properties"]
            assert "key" in params["required"]

    def test_include_filter(self, tmp_path: Path):
        store = JSONMemoryStore(tmp_path / "m.json")
        tools = memory_tools(store, include=("recall_fact",))
        assert len(tools) == 1
        assert tools[0].name == "recall_fact"

    def test_include_unknown_name_raises(self, tmp_path: Path):
        store = JSONMemoryStore(tmp_path / "m.json")
        with pytest.raises(ValueError):
            memory_tools(store, include=("bogus_tool",))

    def test_two_stores_stay_isolated(self, tmp_path: Path):
        a = JSONMemoryStore(tmp_path / "a.json")
        b = JSONMemoryStore(tmp_path / "b.json")
        rem_a, _, _ = memory_tools(a)
        rem_b, _, _ = memory_tools(b)
        rem_a.call({"key": "k", "value": "from-a"})
        rem_b.call({"key": "k", "value": "from-b"})
        assert a.get_fact("k") == "from-a"
        assert b.get_fact("k") == "from-b"

    def test_scoped_remember_and_forget(self, tmp_path: Path):
        store = JSONMemoryStore(tmp_path / "m.json")
        remember, forget, _ = memory_tools(store)
        remember.call({"key": "pref", "value": "spicy", "scope": "user"})
        remember.call({"key": "pref", "value": "mild", "scope": "env:kitchen"})
        assert store.get_fact("pref", scope="user") == "spicy"
        assert store.get_fact("pref", scope="env:kitchen") == "mild"
        forget.call({"key": "pref", "scope": "user"})
        assert store.get_fact("pref", scope="user") is None
        # The kitchen-scoped fact survives — scoping is genuinely
        # honoured end-to-end.
        assert store.get_fact("pref", scope="env:kitchen") == "mild"

    def test_tools_remain_callable_after_store_reopen(self, tmp_path: Path):
        """The tool closure holds a reference to the store; reopening
        the store (fresh instance pointing at the same file) does
        NOT invalidate the closure — the old tool still writes to
        the original in-memory store. This is by design: if you want
        a different store, rebuild the tools."""
        path = tmp_path / "m.json"
        store = JSONMemoryStore(path)
        remember, _, _ = memory_tools(store)
        remember.call({"key": "k", "value": "v1"})
        store.flush()
        # Reopen under a new instance — it reads the on-disk state.
        fresh = JSONMemoryStore(path)
        assert fresh.get_fact("k") == "v1"
        # The old ``remember`` is still bound to the OLD store instance.
        remember.call({"key": "k", "value": "v2"})
        assert store.get_fact("k") == "v2"
        # The fresh store hasn't been reloaded and so still holds v1.
        assert fresh.get_fact("k") == "v1"


# ---------------------------------------------------------------------------
# SQLiteMemoryStore
# ---------------------------------------------------------------------------


class TestSQLiteMemoryStore:
    def test_add_and_get_fact(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.add_fact("user.name", "Ada")
        assert s.get_fact("user.name") == "Ada"
        s.close()

    def test_overwrite_invalidates_prior_keeps_history(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.add_fact("temp", "20")
        time.sleep(0.01)
        s.add_fact("temp", "22")
        assert s.get_fact("temp") == "22"
        hist = s.fact_history("temp")
        assert len(hist) == 2
        assert hist[0].value == "20"
        assert hist[0].valid_to is not None
        assert hist[0].invalidated_at is not None
        assert hist[1].value == "22"
        assert hist[1].supersedes == hist[0].id
        s.close()

    def test_same_value_rewrite_is_noop_refresh(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.add_fact("k", "v")
        [before] = s.fact_history("k")
        old_updated = before.updated_at
        time.sleep(0.01)
        s.add_fact("k", "v")  # identical value
        hist = s.fact_history("k")
        assert len(hist) == 1
        assert hist[0].updated_at > old_updated
        s.close()

    def test_forget_fact_marks_not_active(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.add_fact("k", "v")
        assert s.forget_fact("k") is True
        assert s.get_fact("k") is None
        # History still holds it.
        assert len(s.fact_history("k")) == 1
        s.close()

    def test_forget_missing_returns_false(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        assert s.forget_fact("never") is False
        s.close()

    def test_facts_as_of_returns_historical_view(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.add_fact("mug.location", "counter")
        t_counter = time.time()
        time.sleep(0.05)
        s.add_fact("mug.location", "drawer")
        t_drawer = time.time()
        # Mid-interval: the counter fact is still believed.
        mid = (t_counter + t_drawer) / 2
        as_of_mid = s.facts_as_of(mid)
        assert len(as_of_mid) == 1
        assert as_of_mid[0].value == "counter"
        # After second write: drawer is the truth.
        as_of_now = s.facts_as_of(time.time() + 1.0)
        assert [f.value for f in as_of_now] == ["drawer"]
        s.close()

    def test_scoped_facts(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.add_fact("name", "Ada", scope="user")
        s.add_fact("name", "Kitchen", scope="env:kitchen")
        user_only = s.facts(scope="user")
        assert {f.key for f in user_only} == {"name"}
        assert user_only[0].value == "Ada"
        all_active = s.facts()
        assert len(all_active) == 2
        s.close()

    def test_preferences_upsert(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.set_preference("voice", "af_heart")
        s.set_preference("voice", "af_bella")  # upsert
        prefs = s.preferences()
        assert len(prefs) == 1
        assert prefs[0].value == "af_bella"
        s.close()

    def test_episodes_bounded_ring(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s._max_episodes = 5  # tighten for the test
        for i in range(12):
            s.add_episode("tick", {"i": i}, "ok")
        recent = s.recent_episodes(n=10)
        assert len(recent) == 5
        # Oldest retained should be i=7 (12 total - 5 kept = 7 dropped).
        payloads = [e.payload["i"] for e in recent]
        assert payloads == [7, 8, 9, 10, 11]
        s.close()

    def test_episodes_filter_by_kind(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.add_episode("grasp", {"obj": "cup"}, "ok")
        s.add_episode("navigate", {"to": "kitchen"}, "ok")
        s.add_episode("grasp", {"obj": "plate"}, "failed")
        grasps = s.recent_episodes(n=10, kind="grasp")
        assert [e.outcome for e in grasps] == ["ok", "failed"]
        s.close()

    def test_render_for_prompt_matches_shape(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.add_fact("user.name", "Ada")
        s.set_preference("lang", "en")
        s.add_episode("grasp", {"obj": "cup"}, "ok")
        rendered = s.render_for_prompt()
        assert "Known preferences" in rendered
        assert "Known facts" in rendered
        assert "Recent outcomes" in rendered
        assert "Ada" in rendered

    def test_persists_across_reopens(self, tmp_path: Path):
        db = tmp_path / "m.db"
        s1 = SQLiteMemoryStore(db)
        s1.add_fact("k", "v")
        s1.close()
        s2 = SQLiteMemoryStore(db)
        assert s2.get_fact("k") == "v"
        s2.close()

    def test_concurrent_writes_do_not_corrupt(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        errors: list[BaseException] = []

        def worker(i: int):
            try:
                for j in range(20):
                    s.add_fact(f"k{i}", f"v{i}-{j}")
            except Exception as exc:
                errors.append(exc)

        threads = [threading.Thread(target=worker, args=(i,)) for i in range(5)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        assert errors == []
        # Each key should land on its final value.
        for i in range(5):
            assert s.get_fact(f"k{i}") == f"v{i}-19"
        s.close()

    def test_close_is_idempotent(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.close()
        s.close()  # must not raise

    def test_passes_memorystore_protocol(self, tmp_path: Path):
        """SQLiteMemoryStore is a structural fit for MemoryStore."""
        from edgevox.agents.memory import MemoryStore

        s = SQLiteMemoryStore(tmp_path / "m.db")
        assert isinstance(s, MemoryStore)
        s.close()

    def test_wal_mode_is_enabled(self, tmp_path: Path):
        """WAL mode is the main promise — concurrent readers alongside
        a writer. Verify the PRAGMA actually took effect."""
        s = SQLiteMemoryStore(tmp_path / "m.db")
        result = s._conn.execute("PRAGMA journal_mode").fetchone()
        assert result[0].lower() == "wal"
        s.close()

    def test_second_reader_sees_committed_writes(self, tmp_path: Path):
        """Two SQLiteMemoryStore instances over the same DB file should
        both see facts written by the other — the multi-process-safe
        promise in WAL mode."""
        db = tmp_path / "m.db"
        writer = SQLiteMemoryStore(db)
        writer.add_fact("k", "v1")
        reader = SQLiteMemoryStore(db)  # second connection, no cross-talk
        assert reader.get_fact("k") == "v1"
        writer.add_fact("k", "v2")
        # ``get_fact`` reads through a fresh SELECT on each call, so
        # the second reader sees the update on the next query.
        assert reader.get_fact("k") == "v2"
        writer.close()
        reader.close()

    def test_valid_from_strictly_increases_across_overwrites(self, tmp_path: Path):
        """Bi-temporal invariant: every fact's valid_from >= the prior
        one's. Tests that the time clamp in add_fact isn't trashing
        ordering on fast consecutive writes."""
        s = SQLiteMemoryStore(tmp_path / "m.db")
        for i in range(5):
            s.add_fact("k", f"v{i}")
            time.sleep(0.002)
        from itertools import pairwise

        hist = s.fact_history("k")
        assert len(hist) == 5
        for a, b in pairwise(hist):
            assert a.valid_from <= b.valid_from, "history must be chronologically ordered"
        s.close()

    def test_facts_as_of_never_returns_a_fact_before_its_valid_from(self, tmp_path: Path):
        s = SQLiteMemoryStore(tmp_path / "m.db")
        s.add_fact("k", "v")
        [only] = s.fact_history("k")
        # A timestamp strictly earlier than valid_from must yield []
        result = s.facts_as_of(only.valid_from - 1.0)
        assert result == []
        s.close()
